package org.example.model.DAO;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

import java.util.List;

public abstract class AbstractDAO<T> {
    protected final SessionFactory sessionFactory;

    public AbstractDAO( SessionFactory sessionFactory) {
        this.sessionFactory = sessionFactory;
    }

    /**
     * Note: For entities with composite keys (like UserRoleDTO, RolePermissionDTO),
     *  use their createWithCompositeKey() instead. This method returns null
     *  for such cases.
     * @param dto the corresponding instantiated DTO (i.e.  eBookDAO -> eBookDTO
     * @return Integer id generated by hibernate
     */
    public Integer create (T dto) {
        Session session = null;
        Transaction tx = null;
        Integer generatedId = null;
        try {
            session = sessionFactory.openSession();
            tx = session.beginTransaction();

            generatedId = (Integer) session.save(dto);

            tx.commit();
        } catch (Exception e) {

            if (tx != null) {
                tx.rollback();
            }

            throw new RuntimeException("Failed to insert the entity", e);
        } finally {

            if (session != null) {
                session.close();
            }
        }
        return generatedId;
    }

    public T read (int id) {
        Session session = null;
        Transaction tx = null;
        try {
            session = sessionFactory.openSession();
            tx = session.beginTransaction();

            T dto = session.get(getDTOClass(), id);

            tx.commit();
            return dto;
        } catch (Exception e) {

            if (tx != null && tx.isActive()) {
                tx.rollback();
            }

            throw new RuntimeException("Failed to read the entity", e);
        } finally {

            if (session != null && session.isOpen()) {
                session.close();
            }
        }
    }

    public void update (T dto) {
        Session session = null;
        Transaction tx = null;
        try {

            session = sessionFactory.openSession();
            tx = session.beginTransaction();

            session.update(dto);

            tx.commit();
        } catch (Exception e) {

            if (tx != null && tx.isActive()) {
                tx.rollback();
            }

            throw new RuntimeException("Failed to update the entity", e);
        } finally {

            if (session != null && session.isOpen()) {
                session.close();
            }
        }

    }

    public void delete (T dto) {
        Session session = null;
        Transaction tx = null;
        try{

            session = sessionFactory.openSession();
            tx = session.beginTransaction();

            session.delete(dto);

            tx.commit();
        }catch (Exception e) {

            if (tx != null && tx.isActive()) {
                tx.rollback();
            }

            throw new RuntimeException("Failed to delete the entity", e);
        }finally{

            if (session != null && session.isOpen()) {
                session.close();
            }
        }
    }

    public void delete (List<T> dtos) {
        Session session = null;
        Transaction tx = null;

        try{

            session = sessionFactory.openSession();
            tx = session.beginTransaction();

            for (T dto : dtos) {
                session.delete(dto);
            }

            tx.commit();
        }catch (Exception e) {

            if (tx != null && tx.isActive()) {
                tx.rollback();
            }

            throw new RuntimeException("Failed to update the entity", e);
        }finally{

            if (session != null && session.isOpen()) {
                session.close();
            }
        }

    }

    /**
     *
     * @return *subclass corresponding DTO class type.*
     * This is required by the read operation (see above) due to java's runtime type erasure.
     * Due to erasure java defaults all type generics (T) to "Object" at runtime if not provided with a type.
     * Thus, each subclass needs to set its corresponding DTO class type so that the object of correct type can be read
     */
    protected abstract Class<T> getDTOClass();


}
